/* dict.js - 词典查询模块 */
(function() {
  'use strict';

  // Simple dictionary lookup using Free Dictionary API
  // Fallback to a basic built-in dictionary for common words
  var DICT_CACHE = {};

  // Built-in mini dictionary for ~200 common考研 words
  var BUILTIN = {
    "abandon": "v. 放弃，抛弃",
    "abstract": "adj. 抽象的 n. 摘要",
    "academic": "adj. 学术的，学院的",
    "accelerate": "v. 加速，促进",
    "access": "n. 进入，通道 v. 访问",
    "accommodate": "v. 容纳，适应",
    "accompany": "v. 陪伴，伴随",
    "accomplish": "v. 完成，实现",
    "accumulate": "v. 积累，积聚",
    "accurate": "adj. 准确的，精确的",
    "achieve": "v. 达到，取得",
    "acknowledge": "v. 承认，确认",
    "acquire": "v. 获得，习得",
    "adapt": "v. 适应，改编",
    "adequate": "adj. 足够的，适当的",
    "adjust": "v. 调整，适应",
    "administration": "n. 管理，行政",
    "adopt": "v. 采用，收养",
    "advance": "v. 前进，推进 n. 进展",
    "advantage": "n. 优势，有利条件",
    "advocate": "v. 提倡，主张 n. 倡导者",
    "affect": "v. 影响，感动",
    "aggressive": "adj. 侵略的，好斗的",
    "allocate": "v. 分配，拨出",
    "alter": "v. 改变，修改",
    "alternative": "n. 替代方案 adj. 替代的",
    "ambiguous": "adj. 模糊的，模棱两可的",
    "analyze": "v. 分析",
    "annual": "adj. 年度的，每年的",
    "anticipate": "v. 预期，期望",
    "apparent": "adj. 明显的，表面上的",
    "approach": "v. 接近，处理 n. 方法",
    "appropriate": "adj. 适当的，合适的",
    "approximate": "adj. 大约的，近似的",
    "arbitrary": "adj. 任意的，武断的",
    "aspect": "n. 方面，层面",
    "assemble": "v. 集合，组装",
    "assess": "v. 评估，评定",
    "assign": "v. 分配，指派",
    "assist": "v. 帮助，协助",
    "associate": "v. 联系，关联 n. 同事",
    "assume": "v. 假设，承担",
    "atmosphere": "n. 气氛，大气层",
    "attach": "v. 附着，附加",
    "attain": "v. 达到，获得",
    "attribute": "v. 归因于 n. 属性",
    "authority": "n. 权威，当局",
    "available": "adj. 可用的，有效的",
    "aware": "adj. 意识到的，知道的",
    "barrier": "n. 障碍，屏障",
    "benefit": "n. 利益，好处 v. 受益",
    "bias": "n. 偏见，偏向",
    "bond": "n. 债券，纽带，联系",
    "brief": "adj. 简短的，短暂的",
    "budget": "n. 预算",
    "capable": "adj. 有能力的",
    "capacity": "n. 能力，容量",
    "category": "n. 类别，种类",
    "cease": "v. 停止，终止",
    "challenge": "n. 挑战 v. 质疑",
    "channel": "n. 渠道，频道",
    "chapter": "n. 章节",
    "characteristic": "n. 特征 adj. 特有的",
    "circumstance": "n. 环境，情况",
    "cite": "v. 引用，引证",
    "civil": "adj. 公民的，民用的，文明的",
    "claim": "v. 声称，要求 n. 索赔",
    "classic": "adj. 经典的，典型的",
    "clause": "n. 条款，从句",
    "coincidence": "n. 巧合",
    "collapse": "v. 崩溃，倒塌",
    "colleague": "n. 同事",
    "comment": "n. 评论，意见",
    "commission": "n. 委员会，佣金",
    "commit": "v. 承诺，犯（罪），投入",
    "commodity": "n. 商品，货物",
    "communicate": "v. 沟通，交流",
    "community": "n. 社区，团体",
    "compatible": "adj. 兼容的，一致的",
    "compensate": "v. 补偿，赔偿",
    "compile": "v. 编译，汇编",
    "complement": "v. 补充 n. 补充物",
    "complex": "adj. 复杂的 n. 综合体",
    "component": "n. 组成部分，组件",
    "comprehensive": "adj. 全面的，综合的",
    "comprise": "v. 包含，由...组成",
    "concentrate": "v. 集中，专注",
    "concept": "n. 概念，观念",
    "conclude": "v. 得出结论，结束",
    "conduct": "v. 进行，实施 n. 行为",
    "conference": "n. 会议，讨论会",
    "confine": "v. 限制，局限",
    "confirm": "v. 确认，证实",
    "conflict": "n. 冲突，矛盾",
    "conform": "v. 符合，遵守",
    "confront": "v. 面对，对抗",
    "conscious": "adj. 有意识的，清醒的",
    "consent": "n. 同意，许可",
    "consequence": "n. 后果，结果",
    "conservative": "adj. 保守的",
    "considerable": "adj. 相当大的，可观的",
    "consistent": "adj. 一致的，始终如一的",
    "constant": "adj. 持续的，不变的",
    "constitute": "v. 构成，组成",
    "construct": "v. 构建，建造",
    "consume": "v. 消费，消耗",
    "contact": "v. 联系 n. 接触",
    "contemporary": "adj. 当代的，同时代的",
    "context": "n. 上下文，语境，背景",
    "contract": "n. 合同 v. 收缩",
    "contradict": "v. 矛盾，反驳",
    "contrary": "adj. 相反的 n. 反面",
    "contrast": "n. 对比，对照",
    "contribute": "v. 贡献，投稿",
    "controversial": "adj. 有争议的",
    "convention": "n. 惯例，大会",
    "convince": "v. 说服，使确信",
    "cooperate": "v. 合作，协作",
    "coordinate": "v. 协调 n. 坐标",
    "core": "n. 核心，要点",
    "corporate": "adj. 公司的，法人的",
    "correspond": "v. 对应，通信",
    "counsel": "v. 建议，劝告 n. 法律顾问",
    "counter": "v. 反对，反击 n. 柜台",
    "counterpart": "n. 对应的人或物",
    "crucial": "adj. 关键的，决定性的",
    "currency": "n. 货币，通货",
    "cycle": "n. 循环，周期",
    "debate": "n. 辩论，争论",
    "decade": "n. 十年",
    "decline": "v. 下降，衰退，拒绝",
    "dedicate": "v. 奉献，致力于",
    "define": "v. 定义，界定",
    "definite": "adj. 明确的，确定的",
    "demonstrate": "v. 展示，证明",
    "deny": "v. 否认，拒绝",
    "deposit": "n. 存款，押金 v. 存放",
    "depress": "v. 使沮丧，压抑",
    "derive": "v. 源自，获得",
    "deserve": "v. 值得，应得",
    "despite": "prep. 尽管，不管",
    "detect": "v. 发现，检测",
    "device": "n. 设备，装置",
    "devote": "v. 致力于，奉献",
    "dimension": "n. 维度，尺寸",
    "diminish": "v. 减少，缩小",
    "discipline": "n. 学科，纪律",
    "discriminate": "v. 歧视，区分",
    "dispose": "v. 处理，处置",
    "dispute": "n. 争议，纠纷",
    "dissolve": "v. 溶解，解散",
    "distinct": "adj. 明显的，独特的",
    "distinguish": "v. 区分，辨别",
    "distribute": "v. 分配，分布",
    "diverse": "adj. 多样的，不同的",
    "document": "n. 文件 v. 记录",
    "domestic": "adj. 国内的，家庭的",
    "dominate": "v. 主导，支配",
    "draft": "n. 草稿 v. 起草",
    "drama": "n. 戏剧，剧本",
    "dramatic": "adj. 戏剧性的，巨大的",
    "dynamic": "adj. 动态的，有活力的",
    "economy": "n. 经济",
    "edition": "n. 版本，版次",
    "efficient": "adj. 高效的",
    "elaborate": "adj. 精心的 v. 详细阐述",
    "element": "n. 元素，要素",
    "eliminate": "v. 消除，淘汰",
    "emerge": "v. 出现，浮现",
    "emphasis": "n. 强调，重点",
    "enable": "v. 使能够，启用",
    "encounter": "v. 遭遇，遇到",
    "enforce": "v. 执行，强制",
    "enhance": "v. 增强，提高",
    "enormous": "adj. 巨大的，庞大的",
    "ensure": "v. 确保，保证",
    "enterprise": "n. 企业，事业",
    "environment": "n. 环境",
    "equation": "n. 方程式，等式",
    "equivalent": "adj. 等价的，相等的",
    "error": "n. 错误，误差",
    "essential": "adj. 本质的，基本的",
    "establish": "v. 建立，确立",
    "estate": "n. 房地产，财产",
    "estimate": "v. 估计，估算",
    "evaluate": "v. 评价，评估",
    "eventually": "adv. 最终，终于",
    "evidence": "n. 证据，迹象",
    "evolution": "n. 进化，演变",
    "evolve": "v. 进化，发展",
    "exceed": "v. 超过，超越",
    "exception": "n. 例外",
    "exclude": "v. 排除，排斥",
    "exclusive": "adj. 独有的，排他的",
    "execute": "v. 执行，实施",
    "exhibit": "v. 展示，展览",
    "expand": "v. 扩展，扩大",
    "expert": "n. 专家 adj. 专业的",
    "exploit": "v. 开发，利用，剥削",
    "export": "v. 出口，输出",
    "expose": "v. 暴露，揭露",
    "extend": "v. 延伸，扩展",
    "external": "adj. 外部的，外来的",
    "extract": "v. 提取，摘录",
    "extreme": "adj. 极端的，极度的",
    "facilitate": "v. 促进，便利",
    "factor": "n. 因素，要素",
    "federal": "adj. 联邦的",
    "feedback": "n. 反馈",
    "figure": "n. 数字，人物 v. 认为",
    "finance": "n. 金融，财政",
    "flexible": "adj. 灵活的，弹性的",
    "forecast": "v. 预测，预报",
    "formal": "adj. 正式的，形式的",
    "format": "n. 格式 v. 格式化",
    "formula": "n. 公式，方案",
    "foundation": "n. 基础，基金会",
    "framework": "n. 框架，结构",
    "function": "n. 功能，函数",
    "fund": "n. 基金，资金",
    "fundamental": "adj. 基本的，根本的",
    "furthermore": "adv. 此外，而且",
    "gender": "n. 性别",
    "generate": "v. 产生，生成",
    "global": "adj. 全球的，整体的",
    "grant": "v. 授予，同意 n. 拨款",
    "guarantee": "v. 保证，担保",
    "guideline": "n. 指导方针",
    "hence": "adv. 因此，所以",
    "highlight": "v. 强调，突出",
    "hypothesis": "n. 假设",
    "identical": "adj. 相同的，同一的",
    "identify": "v. 识别，确认",
    "ideology": "n. 意识形态，思想体系",
    "ignorance": "n. 无知",
    "illustrate": "v. 说明，举例说明",
    "image": "n. 图像，形象",
    "immigrant": "n. 移民",
    "impact": "n. 影响，冲击",
    "implement": "v. 实施，执行",
    "implication": "n. 含义，暗示",
    "implicit": "adj. 含蓄的，隐含的",
    "imply": "v. 暗示，意味着",
    "impose": "v. 强加，征收",
    "incentive": "n. 激励，动机",
    "incident": "n. 事件，事故",
    "incorporate": "v. 包含，合并",
    "index": "n. 索引，指数",
    "indicate": "v. 表明，指示",
    "individual": "n. 个人 adj. 个人的",
    "inevitable": "adj. 不可避免的",
    "infrastructure": "n. 基础设施",
    "initial": "adj. 最初的，开始的",
    "initiative": "n. 主动性，倡议",
    "innovation": "n. 创新",
    "insert": "v. 插入，嵌入",
    "insight": "n. 洞察力，见解",
    "inspect": "v. 检查，视察",
    "instance": "n. 实例，例子",
    "institute": "n. 机构，学院",
    "integrate": "v. 整合，集成",
    "intellectual": "adj. 智力的 n. 知识分子",
    "intelligence": "n. 智力，情报",
    "intense": "adj. 强烈的，紧张的",
    "interact": "v. 互动，相互作用",
    "interfere": "v. 干涉，干扰",
    "internal": "adj. 内部的，国内的",
    "interpret": "v. 解释，口译",
    "interval": "n. 间隔，间歇",
    "intervene": "v. 干预，介入",
    "invest": "v. 投资",
    "investigate": "v. 调查，研究",
    "involve": "v. 涉及，包含",
    "isolate": "v. 隔离，孤立",
    "issue": "n. 问题，议题 v. 发布",
    "item": "n. 项目，条款",
    "journal": "n. 期刊，日志",
    "justify": "v. 证明...正当",
    "label": "n. 标签 v. 标注",
    "labor": "n. 劳动，劳工",
    "layer": "n. 层，层次",
    "lecture": "n. 讲座，演讲",
    "legal": "adj. 法律的，合法的",
    "legislation": "n. 立法，法规",
    "liberal": "adj. 自由的，开明的",
    "license": "n. 许可证，执照",
    "likewise": "adv. 同样地",
    "link": "v. 连接，联系 n. 链接",
    "literary": "adj. 文学的",
    "loan": "n. 贷款，借款",
    "locate": "v. 定位，位于",
    "logic": "n. 逻辑",
    "maintain": "v. 维持，保持",
    "major": "adj. 主要的 n. 专业",
    "manifest": "v. 表明，显示 adj. 明显的",
    "manipulate": "v. 操纵，操作",
    "margin": "n. 边缘，利润",
    "measure": "v. 测量 n. 措施",
    "mechanism": "n. 机制，原理",
    "medium": "n. 媒介，方法 adj. 中等的",
    "mental": "adj. 精神的，心理的",
    "military": "adj. 军事的 n. 军队",
    "minimal": "adj. 最小的，最低限度的",
    "minimum": "n. 最小值 adj. 最小的",
    "ministry": "n. (政府的)部",
    "minor": "adj. 较小的，次要的",
    "mode": "n. 模式，方式",
    "modify": "v. 修改，修饰",
    "monitor": "v. 监控 n. 监视器",
    "motive": "n. 动机，目的",
    "mutual": "adj. 相互的，共同的",
    "negative": "adj. 消极的，否定的",
    "neglect": "v. 忽视，忽略",
    "network": "n. 网络",
    "nevertheless": "adv. 然而，不过",
    "norm": "n. 规范，标准",
    "notion": "n. 概念，观念",
    "nuclear": "adj. 核的，核心的",
    "objective": "n. 目标 adj. 客观的",
    "obtain": "v. 获得，得到",
    "obvious": "adj. 明显的",
    "occupy": "v. 占据，占用",
    "occur": "v. 发生，出现",
    "odd": "adj. 奇怪的，奇数的",
    "offend": "v. 冒犯，得罪",
    "option": "n. 选择，选项",
    "outcome": "n. 结果，结局",
    "output": "n. 产出，输出",
    "overall": "adj. 总体的，全面的",
    "overcome": "v. 克服，战胜",
    "overlap": "v. 重叠，重复",
    "overseas": "adj. 海外的 adv. 在国外",
    "panel": "n. 面板，专门小组",
    "paradigm": "n. 范例，典范",
    "paragraph": "n. 段落",
    "parallel": "adj. 平行的，类似的",
    "participate": "v. 参与，参加",
    "partner": "n. 伙伴，合伙人",
    "passive": "adj. 被动的，消极的",
    "perceive": "v. 感知，察觉",
    "period": "n. 时期，周期",
    "persist": "v. 坚持，持续",
    "perspective": "n. 视角，观点",
    "phase": "n. 阶段，时期",
    "phenomenon": "n. 现象",
    "philosophy": "n. 哲学",
    "physical": "adj. 物理的，身体的",
    "policy": "n. 政策，方针",
    "portion": "n. 部分，一份",
    "pose": "v. 造成，提出，摆姿势",
    "positive": "adj. 积极的，肯定的",
    "potential": "adj. 潜在的 n. 潜力",
    "poverty": "n. 贫穷，贫困",
    "precise": "adj. 精确的，准确的",
    "predict": "v. 预测，预言",
    "prejudice": "n. 偏见，歧视",
    "preserve": "v. 保护，保存",
    "previous": "adj. 以前的，先前的",
    "primary": "adj. 主要的，初级的",
    "principal": "adj. 主要的 n. 校长",
    "principle": "n. 原则，原理",
    "prior": "adj. 先前的，优先的",
    "priority": "n. 优先，优先事项",
    "procedure": "n. 程序，步骤",
    "proceed": "v. 继续进行",
    "process": "n. 过程 v. 处理",
    "professional": "adj. 专业的，职业的",
    "profit": "n. 利润，收益",
    "prohibit": "v. 禁止，阻止",
    "project": "n. 项目 v. 投影，预测",
    "promote": "v. 促进，提升",
    "proportion": "n. 比例，部分",
    "prospect": "n. 前景，展望",
    "protein": "n. 蛋白质",
    "protest": "v. 抗议，反对",
    "provision": "n. 规定，条款，供应",
    "psychological": "adj. 心理的",
    "publish": "v. 出版，发布",
    "purchase": "v. 购买 n. 购买物",
    "pursue": "v. 追求，从事",
    "qualify": "v. 使合格，限定",
    "quote": "v. 引用，报价",
    "radical": "adj. 根本的，激进的",
    "random": "adj. 随机的，任意的",
    "range": "n. 范围 v. 变化",
    "ratio": "n. 比率，比例",
    "rational": "adj. 理性的，合理的",
    "react": "v. 反应，回应",
    "recover": "v. 恢复，康复",
    "register": "v. 注册，登记",
    "regulate": "v. 调节，管理",
    "reinforce": "v. 加强，强化",
    "reject": "v. 拒绝，排斥",
    "release": "v. 释放，发布",
    "relevant": "adj. 相关的",
    "reluctant": "adj. 不情愿的，勉强的",
    "rely": "v. 依赖，依靠",
    "remove": "v. 移除，消除",
    "render": "v. 使成为，提供",
    "represent": "v. 代表，表示",
    "require": "v. 需要，要求",
    "reserve": "v. 保留，预订",
    "resident": "n. 居民 adj. 居住的",
    "resolve": "v. 解决，决定",
    "resource": "n. 资源",
    "respond": "v. 回应，响应",
    "restore": "v. 恢复，修复",
    "restrain": "v. 抑制，约束",
    "restrict": "v. 限制，约束",
    "retain": "v. 保留，保持",
    "reveal": "v. 揭示，透露",
    "revenue": "n. 收入，税收",
    "reverse": "v. 反转，颠倒",
    "revolution": "n. 革命，变革",
    "rigid": "adj. 僵硬的，严格的",
    "role": "n. 角色，作用",
    "route": "n. 路线，途径",
    "scenario": "n. 场景，方案",
    "schedule": "n. 时间表，日程",
    "scheme": "n. 方案，计划",
    "scope": "n. 范围，视野",
    "section": "n. 部分，章节",
    "sector": "n. 部门，领域",
    "secure": "adj. 安全的 v. 获得",
    "seek": "v. 寻求，寻找",
    "select": "v. 选择 adj. 精选的",
    "senior": "adj. 高级的，年长的",
    "sequence": "n. 序列，顺序",
    "series": "n. 系列，连续",
    "shift": "v. 转移，转变 n. 轮班",
    "significant": "adj. 重要的，显著的",
    "similar": "adj. 相似的，类似的",
    "site": "n. 地点，场所",
    "sole": "adj. 唯一的，单独的",
    "somewhat": "adv. 有点，稍微",
    "source": "n. 来源，出处",
    "specific": "adj. 具体的，特定的",
    "sphere": "n. 领域，范围，球体",
    "stable": "adj. 稳定的",
    "statistics": "n. 统计，统计学",
    "status": "n. 地位，状态",
    "strategy": "n. 策略，战略",
    "stress": "n. 压力 v. 强调",
    "structure": "n. 结构，构造",
    "submit": "v. 提交，服从",
    "subsequent": "adj. 随后的，后来的",
    "substitute": "v. 替代 n. 替代品",
    "sufficient": "adj. 足够的，充分的",
    "sum": "n. 总和，金额",
    "summary": "n. 总结，摘要",
    "superior": "adj. 优越的，上级的",
    "supplement": "v. 补充 n. 补充物",
    "survey": "n. 调查，测量",
    "survive": "v. 幸存，生存",
    "suspend": "v. 暂停，悬挂",
    "sustain": "v. 维持，支撑",
    "symbol": "n. 符号，象征",
    "target": "n. 目标 v. 以...为目标",
    "task": "n. 任务，工作",
    "technique": "n. 技术，技巧",
    "technology": "n. 技术，科技",
    "temporary": "adj. 暂时的，临时的",
    "tend": "v. 倾向于，趋向",
    "tense": "adj. 紧张的 n. 时态",
    "terminal": "n. 终端，终点站",
    "text": "n. 文本，课文",
    "theme": "n. 主题，题目",
    "theory": "n. 理论，学说",
    "thereby": "adv. 因此，从而",
    "topic": "n. 话题，主题",
    "trace": "v. 追踪，追溯 n. 痕迹",
    "tradition": "n. 传统，惯例",
    "transfer": "v. 转移，转让",
    "transform": "v. 转变，改造",
    "transmit": "v. 传输，传播",
    "trend": "n. 趋势，倾向",
    "trigger": "v. 触发，引起",
    "ultimate": "adj. 最终的，根本的",
    "undergo": "v. 经历，经受",
    "underline": "v. 强调，在...下划线",
    "undertake": "v. 承担，从事",
    "unique": "adj. 独特的，唯一的",
    "utilize": "v. 利用，使用",
    "valid": "adj. 有效的，合理的",
    "vary": "v. 变化，不同",
    "vehicle": "n. 车辆，工具",
    "version": "n. 版本，说法",
    "via": "prep. 通过，经由",
    "virtual": "adj. 虚拟的，实质上的",
    "visible": "adj. 可见的，明显的",
    "vision": "n. 视力，愿景",
    "visual": "adj. 视觉的，可视的",
    "volume": "n. 体积，音量，卷",
    "voluntary": "adj. 自愿的，志愿的",
    "welfare": "n. 福利，幸福",
    "whereas": "conj. 然而，鉴于",
    "widespread": "adj. 广泛的，普遍的",
    "yield": "v. 产生，屈服 n. 产量"
  };

  // Look up word in built-in dictionary
  function lookupBuiltin(word) {
    var lower = word.toLowerCase().trim();
    if (BUILTIN[lower]) return BUILTIN[lower];
    // Check if word is in the keys with slightly different forms
    for (var key in BUILTIN) {
      if (key.startsWith(lower) && key.length <= lower.length + 3) {
        return BUILTIN[key];
      }
    }
    return null;
  }

  // Look up word using Free Dictionary API
  function lookupAPI(word) {
    return new Promise(function(resolve, reject) {
      var cacheKey = word.toLowerCase().trim();
      if (DICT_CACHE[cacheKey]) {
        resolve(DICT_CACHE[cacheKey]);
        return;
      }

      var xhr = new XMLHttpRequest();
      xhr.open('GET', 'https://api.dictionaryapi.dev/api/v2/entries/en/' + encodeURIComponent(cacheKey), true);
      xhr.timeout = 5000;
      xhr.onload = function() {
        if (xhr.status === 200) {
          try {
            var data = JSON.parse(xhr.responseText);
            if (data && data.length > 0) {
              var meanings = [];
              data[0].meanings.forEach(function(m) {
                if (m.definitions && m.definitions.length > 0) {
                  var def = m.definitions[0].definition;
                  var pos = m.partOfSpeech || '';
                  meanings.push((pos ? pos + '. ' : '') + def);
                }
              });
              var result = meanings.slice(0, 2).join('；');
              DICT_CACHE[cacheKey] = result;
              resolve(result);
              return;
            }
          } catch (e) {}
        }
        resolve(null);
      };
      xhr.onerror = function() { resolve(null); };
      xhr.ontimeout = function() { resolve(null); };
      xhr.send();
    });
  }

  // Main lookup: built-in first, then API
  window.VocabDict = {
    lookup: function(word) {
      var builtin = lookupBuiltin(word);
      if (builtin) return Promise.resolve(builtin);
      return lookupAPI(word).then(function(result) {
        return result || '';
      });
    },

    lookupBatch: function(words) {
      return Promise.all(words.map(function(w) {
        return window.VocabDict.lookup(w).then(function(meaning) {
          return { word: w, meaning: meaning };
        });
      }));
    },

    // Check if word exists in built-in
    hasBuiltin: function(word) {
      return lookupBuiltin(word) !== null;
    }
  };
})();